# This file was generated by GoReleaser. DO NOT EDIT.
cask "fm" do
  version "0.34.1"

  on_macos do
    on_intel do
      sha256 "fade1e14bc94d069127280f6cdeb9fecb19dffb9587108f77a3a8057fa0748fa"
      url "https://get.frostmoln.cloud/cli/v#{version}/fm-#{version}-darwin-amd64.tar.gz",
        verified: "get.frostmoln.cloud/cli/"
    end
    on_arm do
      sha256 "7a77d17a40196b5e11ebd5befd87b74af4e26996947b59d5d75fdd15357971a2"
      url "https://get.frostmoln.cloud/cli/v#{version}/fm-#{version}-darwin-arm64.tar.gz",
        verified: "get.frostmoln.cloud/cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "6376f1ed33b01f59b38e3676384c0ee0aa70ecc7074c9f43148c43bcf6e02322"
      url "https://get.frostmoln.cloud/cli/v#{version}/fm-#{version}-linux-amd64.tar.gz",
        verified: "get.frostmoln.cloud/cli/"
    end
    on_arm do
      sha256 "58e3d630cc10cb97a9ec1a2386a8b728b0a275ae52b5ae951b6d6a1ab0dc9fb7"
      url "https://get.frostmoln.cloud/cli/v#{version}/fm-#{version}-linux-arm64.tar.gz",
        verified: "get.frostmoln.cloud/cli/"
    end
  end

  name "fm"
  desc "CLI for the Frostmoln Cloud Platform"
  homepage "https://frostmoln.cloud"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fm"
  bash_completion "completions/fm.bash"
  fish_completion "completions/fm.fish"
  zsh_completion "completions/fm.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fm"]
    end
  end

  # No zap stanza required

end
