# This file was generated by GoReleaser. DO NOT EDIT.
cask "fm" do
  version "0.19.6"

  on_macos do
    on_intel do
      sha256 "c6b351ed85c70fca25fbe4fd465ceb1951535e76dd9efacd790f6538feee80f3"
      url "https://get.frostmoln.cloud/cli/v#{version}/fm-#{version}-darwin-amd64.tar.gz",
        verified: "get.frostmoln.cloud/cli/"
    end
    on_arm do
      sha256 "c3f7d199359ad14ba941be57da9a502f8d0418686da156894ab556b50ea3b718"
      url "https://get.frostmoln.cloud/cli/v#{version}/fm-#{version}-darwin-arm64.tar.gz",
        verified: "get.frostmoln.cloud/cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "92fb1d72a37863f1691b11c7c724c55543ae30d11d95bafc07eacb571803f6c3"
      url "https://get.frostmoln.cloud/cli/v#{version}/fm-#{version}-linux-amd64.tar.gz",
        verified: "get.frostmoln.cloud/cli/"
    end
    on_arm do
      sha256 "da3963e8444a508db240957c8e7bbc9824082393750258b1dc9b1ac052b4a7d2"
      url "https://get.frostmoln.cloud/cli/v#{version}/fm-#{version}-linux-arm64.tar.gz",
        verified: "get.frostmoln.cloud/cli/"
    end
  end

  name "fm"
  desc "CLI for the Frostmoln Cloud Platform"
  homepage "https://frostmoln.cloud"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fm"
  bash_completion "completions/fm.bash"
  fish_completion "completions/fm.fish"
  zsh_completion "completions/fm.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fm"]
    end
  end

  # No zap stanza required

end
