# This file was generated by GoReleaser. DO NOT EDIT.
cask "fm" do
  version "0.74.0"

  on_macos do
    on_intel do
      sha256 "5ec3c5963e9eda1662cd9f13675fdb682c5f7e0ea38b864f3894ac3d508c6e6b"
      url "https://get.frostmoln.cloud/cli/v#{version}/fm-#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "ea30abbef720fcbbac43cb6ebdd56ecf712480d0c377c94d763ed1424d12f6d8"
      url "https://get.frostmoln.cloud/cli/v#{version}/fm-#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8b0ad2c3a1527de5e261769c1a9fd1c4759af1a5029dabe8ad5995d190d70991"
      url "https://get.frostmoln.cloud/cli/v#{version}/fm-#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "dc914c67a75f043066025821875d6506516bdc0ce6ba786254d53e8f1a6f436d"
      url "https://get.frostmoln.cloud/cli/v#{version}/fm-#{version}-linux-arm64.tar.gz"
    end
  end

  name "fm"
  desc "CLI for the Frostmoln Cloud Platform"
  homepage "https://frostmoln.cloud"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fm"
  bash_completion "completions/fm.bash"
  fish_completion "completions/fm.fish"
  zsh_completion "completions/fm.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fm"]
    end
  end

  # No zap stanza required

end
